### ISSUE TITLE
Add javadoc & source to maven artifacts 🚀

### ISSUE THREAD

**Issue by Akiranya** [Phoenix616/ConnectorPlugin#7]
#### Is your feature request related to a problem? Please describe.

The maven repo currently doesn't contain javadoc/source artifacts, making it a bit of hard to look up the code within IDE.

#### Describe alternatives you've considered

Though it's possible to look up the online javadoc website, it would be much simpler to just look up from within the IDE.

Furthermore, the website loading speed is a bit slower for me, probably I'm too far from the web server ... :(

Productivity ++🚀🚀🚀🚀🚀

#### Additional context

Btw thanks for the amazing plugin library!

**Comment by Phoenix616** [comment]
Javadocs should've already been included in the maven repo, sources are there now too.
