### ISSUE TITLE
Sending command to velocity not working

### ISSUE THREAD

**Issue by DuneSciFye** [Phoenix616/ConnectorPlugin#8]
Trying to make a command run on the velocity proxy from the spigot subserver, but it's not doing anything
![image](https://github.com/Phoenix616/ConnectorPlugin/assets/65089425/a1345a64-9f49-47c6-95dd-8dbe41e33aee)
![image](https://github.com/Phoenix616/ConnectorPlugin/assets/65089425/584d52c2-1c79-45a9-9428-bc3bab85237e)

**Comment by Phoenix616** [comment]
If this is still an issue please provide more information here like your configs and general setup design.
